### ISSUE TITLE
Problem with migration in Django 2.1.7

### ISSUE THREAD

**Issue by acriptis** [Atterratio/cmsplugin-slick#4]
Hello Everybody!
I tried to install cmsplugin-slick in Django 2.1.7 and stucked with the problem:
First I was migrating and catched exception on `migrate`:
```
(.venv3) alx@lol:~/gonzo/wwwgonzales$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/cmsplugin_slick/models.py", line 45, in <module>
    class SlickCarouselPreset(models.Model):
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/cmsplugin_slick/models.py", line 101, in SlickCarouselPreset
    slick_theme = FilerFileField(verbose_name=_('Slick theme file'), blank=True, null=True)
  File "/home/alx/gonzo/.venv3/lib/python3.6/site-packages/filer/fields/file.py", line 136, in __init__
    super(FilerFileField, self).__init__(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```
I fixed the code of django-filer by providing `on_delete=models.CASCADE`, then I stuck with the following Error in this project:
```
(.venv3) alx@lol:~/gonzo/wwwgonzales$ python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
<class 'cmsplugin_slick.admin.SlickCarouselPresetAdmin'>: (admin.E012) There are duplicate field(s) in 'fieldsets[3][1]'.

```
Does anyone touch this error or have solution?

**Comment by acriptis** [comment]
Will be fixed with https://github.com/Atterratio/cmsplugin-slick/pull/5
